### ISSUE TITLE
An `extra` field to hold additional properties is not generated when `additionalProperties: true`

### ISSUE THREAD

**Issue by lemvik** [oxidecomputer/progenitor#1064]
### Current behaviour

Given the following piece of schema:

```yaml
components:
  schemas:
    Location:
      type: object
      properties:
        lat:
          description: Latitude
          type: number
        lon:
          description: Longitude
          type: number
      required:
        - lat
        - lon
      additionalProperties: true
```

`progenitor` (0.9.1) generates this struct:

```rust
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct Location {
        pub lat: f64,
        pub lon: f64,
    }
```

So there is no `extra` field here so no additional properties are actually captured.

The schema I used is derived from [this recipe](https://swagger.io/docs/specification/v3_0/data-models/dictionaries/#fixed-keys) in order to generate an object that has some fixed keys and some additional keys.

### Expected

What I hoped to get is something along these lines:
```rust
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct Location {
        pub lat: f64,
        pub lon: f64,
        #[serde(flatten)]
        pub extra: ::std::collections::HashMap<::std::string::String, ::serde_json::Value>,
    } 
```

So `extra` field can be used to send/receive/propagate additional properties that I'm not interested in.

### Notes

Using `additionalProperties: { type: object }` causes `progenitor` to generate something close but not exactly what I need:
```rust
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct Location {
        pub lat: f64,
        pub lon: f64,
        #[serde(flatten)]
        pub extra: ::std::collections::HashMap<
            ::std::string::String,
            ::serde_json::Map<::std::string::String, ::serde_json::Value>,
        >,
    }
```
