### ISSUE TITLE
Headers not supported

### ISSUE THREAD

**Issue by jayvdb** [oxidecomputer/progenitor#255]
https://github.com/oxidecomputer/progenitor/blob/4e2dcc5/progenitor-impl/src/method.rs#L330
e.g. I have a header which allows telling the backend the API version the client is expecting.
```yaml
  parameters:
    APIVersionParameterHeader:
      name: X-Foo-ApiVersion
      in: header
      required: false
      schema:
        type: string
```
