### ISSUE TITLE
PagerDuty REST Api generation fails

### ISSUE THREAD

**Issue by nikolay-te** [oxidecomputer/progenitor#591]
I'm trying to use `progenitor` to generate a PagerDuty API client using their published OpenAPI v3 spec from here [openapiv3.json](https://raw.githubusercontent.com/PagerDuty/api-schema/main/reference/REST/openapiv3.json)

I have these dependencies in my `Cargo.toml`:
```toml
[dependencies]
futures = "0.3"
progenitor = { version = "0.4" }
reqwest = { version = "0.11", features = ["json", "stream"] }
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.0.0", features = ["serde", "v4"] }
base64 = "0.21"
rand = "0.8"
regress = "0.7"
```

And a simple `lib.rs`:
```rust
use progenitor::generate_api;

generate_api!("spec/openapiv3.json");
```

However when running `cargo build` I get this error:

```text
error: proc macro panicked
 --> pagerduty/src/lib.rs:3:1
  |
3 | generate_api!("spec/openapiv3.json");
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: message: not clear what we could usefully do here Schema {
              schema_data: SchemaData {
                  nullable: false,
                  read_only: false,
                  write_only: false,
                  deprecated: false,
                  external_docs: None,
                  example: None,
                  title: None,
                  description: None,
                  discriminator: None,
                  default: None,
                  extensions: {},
              },
              schema_kind: Any(
                  AnySchema {
                      typ: None,
                      pattern: None,
                      multiple_of: None,
                      exclusive_minimum: None,
                      exclusive_maximum: None,
                      minimum: None,
                      maximum: None,
                      properties: {},
                      required: [],
                      additional_properties: None,
                      min_properties: None,
                      max_properties: None,
                      items: None,
                      min_items: None,
                      max_items: None,
                      unique_items: None,
                      enumeration: [
                          String("event_orchestration_reference"),
                      ],
                      format: None,
                      min_length: None,
                      max_length: None,
                      one_of: [],
                      all_of: [],
                      any_of: [],
                      not: None,
                  },
              ),
          }

error: could not compile `pagerduty` (lib) due to previous error
```
