### ISSUE TITLE
Generate failed for Xero Accounting OpenAPI spec

### ISSUE THREAD

**Issue by dunxen** [oxidecomputer/progenitor#955]
Hey, thanks for the awesome tool! 💚 

It seems that `cargo-progenitor` (as of [2f32cde](https://github.com/oxidecomputer/progenitor/commit/2f32cdefc28f4b0eb6b3fc53f6f32aaed24d755a), but probably all prior versions 🤷) fails to generate a crate for the [Xero Accounting OpenAPI spec](https://github.com/XeroAPI/Xero-OpenAPI/blob/e2bf47157050335cb2d67679bb7ed217f696742c/xero_accounting.yaml).

After downloading the above spec to reproduce, run:

```bash
RUST_BACKTRACE="full" cargo progenitor -i xero_accounting.yaml -o xero-client -n xero-client -v 6.3.0
```

The output is as follows:

```
gen fail: TypeError(InvalidValue)
Error: generation experienced errors

Stack backtrace:
   0: anyhow::error::<impl anyhow::Error>::msg
   1: cargo_progenitor::main
   2: std::sys::backtrace::__rust_begin_short_backtrace
   3: std::rt::lang_start::{{closure}}
   4: std::rt::lang_start_internal
   5: main
   6: __libc_start_call_main
   7: __libc_start_main_alias_2
   8: _start
```

**Comment by ahl** [comment]
I'll need to look more closely, but I suspect it might be constructs such as this:

```yaml
        HasAttachments:
          description: boolean to indicate if an account has an attachment (read only)
          readOnly: true
          type: boolean
          default: "false"
          example: "false"
```

In particular, the default value is a string `"false"` which may be failing the validation against the schema, i.e. a `boolean`. This is speculation and requires some validation.
